### ISSUE TITLE
Part III

### ISSUE THREAD

**Issue by chr66475** [bgeta/BetelihemGetachew_MADA-project#2]
**Overall Score:** 2 

**Error(s):** 

1. "Error in View: object 'df_rawdata2' not found" - File: processingcode.R | Location: Line 94.
2. "Error in (function (classes,fdef, mtable) : unable to find an inherited method for function 'Summary' for signature'"haven_labelled"'" - File: processingcode.R | Location: Line139
3. "Error in (function (classes,fdef, mtable) : unable to find an inherited method for function 'Summary' for signature'"haven_labelled"'" - File: processingcode.R | Location: Line140
4. "Error in processeddata %>% ggplot(aes(x = HSI, y = B04, fill = HSI)) + : could not find function "+<-"" - File: exploratorycodeR.R | Location: Line 98
5. "Error in plot(figure1) : object 'figure1' not found" - File: exploratorycodeR.R | Location: Line 99
6. "Error in plot_theme(plot) : object 'figure1' not found" - File: exploratorycodeR.R | Location: Line 101
7. "Error in title("HSI and Age of smoking Initiation") : plot.new has not been called yet" File: exploratorycodeR.R | Location: Line 105
8. "Error in eval(predvars, data, env) : object 'Height' not found" - File: statistical_analysis.R | Location: Line 28
9. "Error in broom::tidy(lmfit1) : object 'lmfit1' not found" - File: statistical_analysis.R | Location: Line 31
10. "Error in print(lmtable1) : object 'lmtable1' not found" - File: statistical_analysis.R | Location: Line 34
11. "Error in saveRDS(lmtable1, file = table_file1) : object 'lmtable1' not found" - File: statistical_analysis.R | Location: Line 38
12. "Error in eval(predvars, data, env) : object 'Height' not found" - File: statistical_analysis.R | Location: Line 44
13. "Error in broom::tidy(lmfit2) : object 'lmfit2' not found" - File: statistical_analysis.R | Location: Line 47
14. "Error in print(lmtable2) : object 'lmtable2' not found" - File: statistical_analysis.R | Location: Line 50
15. "Error in saveRDS(lmtable2, file = table_file2) : object 'lmtable2' not found" - File: statistical_analysis.R | Location: Line 54

**Comments:**
Hi Betelihem, your manuscript runs beautifully and I really enjoyed your figures/graphics as well as your written analysis. However, I've tried to run your processingcode.R, exploratorycodeR.R, and statistical_analysis.R files as instructed in your README file, and I ran into the aforementioned errors. I'm unsure if it's just me despite attempting multiple times to run and rerun these files, however, I would recommend using R Markdown files or Quarto Documents while organizing your code in chucks that can easily be run all at once and that makes what you're trying to do more clear for reproducibility. Further, I noticed that in your statistical_analysis.R file you were attempting to build models using an outcome variable and predictor that is not in the dataset you referenced in your code.

**Comment by bgeta** [comment]
Hi Connor, 
I really appreciate your comments and feedbacks. I did realize running selected codes in chunk made the codes run smoother than running the whole code all at once. Thank you for giving me an alternative option by using R Markdown, I will make the updates. 
Thanks
Betelihem
