### ISSUE TITLE
Part 3 Feedback

### ISSUE THREAD

**Issue by okichris90** [bgeta/BetelihemGetachew_MADA-project#3]
Hi Beth, 

I enjoyed reading about your project. Your research question is intriguing, and I'm particularly interested in discovering the predictors of high nicotine dependence among adult smokers in Botswana. 

I found the visuals in your analysis to be helpful in understanding your sample data. 

Here are three suggestions I would like to offer:
 
1. I suggest utilizing the syntax below for creating tables. The output from this code requires minimal editing in the manuscript and can save you significant time.
 
library(table1)
(table1(~ factor(sex) + age + factor(race) + factor(hispanic) | flu_vaccine, data=mydata2))

2. I see that you have models in your results folder. To print the model results on your manuscript, you can use the below syntax.

result_model <- readRDS(here("results", "demographics_model.rds"))
result_model

3. I also will suggest updating the readme files in each folder. 

Overall, your analysis is heading in the right direction, and I am eager to read your final results. 

**Grade: 3/3**

**Comment by bgeta** [comment]
Hi Chris, 
I appreciate your feedback! These are all great suggestions that I will utilize as I work through this project.
Thank you
Beth

**Comment by bgeta** [comment]
Thanks again Chris!
