### ISSUE TITLE
Feedback Part 3 -- Hemme

### ISSUE THREAD

**Issue by hayhem** [bgeta/BetelihemGetachew_MADA-project#4]
I appreciated your very detailed comments! They were especially helpful in following along with your code. I also really enjoyed your visualizations, particularly the mosaic plots.

A few suggestions:
I would reorder HSI so that the levels are low, medium, high, or visa versa -- this would be especially helpful when visualizing the mosaic plots.
Readme files should be updated and/ or removed where necessary
Similarly, several files from the template should be deleted (processinggfiles; slides; etc.)

Some things that I noticed while running through your code. 
-	I'm not familiar with using your definition of B01 + B07 to define a heavy smoker, but I was curious how the maximum value could be 10, when it seemed like the highest value for each is 3 and 4. After doing some digging, I found that some of your values for B07 are "9", might reflect a missing, refused, or unknown value. I saw that you ultimately removed these observations, but you might also consider imputing what these values should be. It is interesting to me that all of these values with B07 == 9 have a B01  == 1.

-The here package is able to set the working directory to the project folder, so some of these lines so a bit redundant. I'm not familiar with read_sav but it's name tells me that it's a probably a tidyverse-compatible function, so that the 'here' step for setting the data path and step load the data likely can be combined.

this code:
setwd('C:/Data/GitHub/MADA23/BetelihemGetachew_MADA-project')
data_location <- here::here("data","raw_data","Botswana.sav")
rawdata<- read_sav(data_location)

The code above can be achieved with:
rawdata <- read_sav(here("data/raw_data/data_location")

I like this method because I can `tab` through folders and files instead of type them in. 

-	Also, using 'filter' would make it easy to consolidate some steps.
 ex:
df_rawdata5<-subset(df_rawdata4, A05!=99)
#check if removed
summary(df_rawdata5$A05)
df_rawdata6<-subset(df_rawdata5, A05!=77)

Could be accomplished with:
df_rawdata6 <- df_rawdata5 %>%
filter(A05 != c(77,99))

I like this method because not only can I filter out multiple observations in a specific column, combine a lot of these steps to make a neat code. 

2/3

**Comment by bgeta** [comment]
Hi there, Thank you so much for your comments and feedback but also for providing alternative codes to improve my codes. I really appreciate it all!
~ Betelihem
